root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

rules:
  '@typescript-eslint/array-type':
    - error
    - default: array-simple

  # TODO: remove and fix next issues
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/require-await': off
  '@typescript-eslint/explicit-module-boundary-types': off
